[package]
name = "shadow-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
shadow-bridge.workspace = true
shadow-cache.workspace = true
shadow-catalog.workspace = true
shadow-core.workspace = true
shadow-domain.workspace = true
shadow-desktop-bridge.workspace = true
shadow-library-sharing.workspace = true
uuid.workspace = true

[lints]
workspace = true
