[package]
name = "shadow-catalog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rusqlite.workspace = true
shadow-domain.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true

