use super::*;
use crate::{OperationId, ParameterKey};

#[test]
fn contract_identifiers_are_valid_domain_names() {
    for operation_id in [
        EXPOSURE_OPERATION_ID,
        CONTRAST_OPERATION_ID,
        OKLAB_LIGHTNESS_TONE_CURVE_OPERATION_ID,
        RGB_WHITE_BALANCE_OPERATION_ID,
        SATURATION_OPERATION_ID,
        SELECTIVE_TONE_OPERATION_ID,
        PERCEPTUAL_COLOR_OPERATION_ID,
        OKLAB_COLOR_WARPER_OPERATION_ID,
        LUT_3D_OPERATION_ID,
        SHARPEN_OPERATION_ID,
        TECHNICAL_DETAIL_OPERATION_ID,
        COLOR_GRADING_OPERATION_ID,
        FINISHING_EFFECTS_OPERATION_ID,
    ] {
        OperationId::new(operation_id).expect("operation contract id must remain valid");
    }

    for parameter_key in [
        EXPOSURE_STOPS_PARAMETER_KEY,
        CONTRAST_FACTOR_PARAMETER_KEY,
        CONTRAST_PIVOT_PARAMETER_KEY,
        WHITE_BALANCE_TEMPERATURE_PARAMETER_KEY,
        WHITE_BALANCE_TINT_PARAMETER_KEY,
        SATURATION_FACTOR_PARAMETER_KEY,
        HIGHLIGHTS_PARAMETER_KEY,
        SHADOWS_PARAMETER_KEY,
        WHITES_PARAMETER_KEY,
        BLACKS_PARAMETER_KEY,
        VIBRANCE_PARAMETER_KEY,
        COLOR_MIXER_HUE_PARAMETER_KEY,
        COLOR_MIXER_SATURATION_PARAMETER_KEY,
        COLOR_MIXER_LIGHTNESS_PARAMETER_KEY,
        COLOR_RANGE_ENABLED_PARAMETER_KEY,
        COLOR_RANGE_CENTER_PARAMETER_KEY,
        COLOR_RANGE_WIDTH_PARAMETER_KEY,
        COLOR_RANGE_SOFTNESS_PARAMETER_KEY,
        COLOR_RANGE_HUE_PARAMETER_KEY,
        COLOR_RANGE_SATURATION_PARAMETER_KEY,
        COLOR_RANGE_LIGHTNESS_PARAMETER_KEY,
        POINT_COLOR_RANGES_PARAMETER_KEY,
        SELECTIVE_COLOR_RELATIVE_PARAMETER_KEY,
        SELECTIVE_COLOR_LIGHTNESS_PROTECTION_PARAMETER_KEY,
        SELECTIVE_COLOR_CMYK_PARAMETER_KEY,
        OKLAB_COLOR_WARPER_CONTROL_POINTS_PARAMETER_KEY,
        OKLAB_COLOR_WARPER_STRENGTH_PARAMETER_KEY,
        LUT_RESOURCE_ID_PARAMETER_KEY,
        LUT_TITLE_PARAMETER_KEY,
        LUT_MANAGED_PATH_PARAMETER_KEY,
        LUT_INTENSITY_PARAMETER_KEY,
        SHARPEN_AMOUNT_PARAMETER_KEY,
        SHARPEN_RADIUS_PARAMETER_KEY,
        SHARPEN_THRESHOLD_PARAMETER_KEY,
        SHARPEN_MASKING_PARAMETER_KEY,
        DETAIL_EFFECTS_PARAMETERS_KEY,
    ] {
        ParameterKey::new(parameter_key)
            .expect("operation contract parameter key must remain valid");
    }
}

#[test]
fn pre_release_operation_contracts_remain_v1() {
    assert_eq!(CPU_REFERENCE_PARAMETER_SCHEMA_VERSION, 1);
    assert_eq!(CPU_REFERENCE_IMPLEMENTATION_REVISION, 1);
    assert_eq!(OKLAB_LIGHTNESS_TONE_CURVE_PARAMETER_SCHEMA_VERSION, 1);
    assert_eq!(SELECTIVE_TONE_PARAMETER_SCHEMA_VERSION, 1);
    assert_eq!(OKLAB_COLOR_WARPER_PARAMETER_SCHEMA_VERSION, 1);
    assert_eq!(TECHNICAL_DETAIL_PARAMETER_SCHEMA_VERSION, 1);
    assert_eq!(COLOR_GRADING_PARAMETER_SCHEMA_VERSION, 1);
    assert_eq!(FINISHING_EFFECTS_PARAMETER_SCHEMA_VERSION, 1);
    assert_eq!(BASIC_GRAPH_SCHEMA_VERSION, 1);

    for identity in [
        CPU_REFERENCE_IMPLEMENTATION_VERSION,
        OKLAB_LIGHTNESS_TONE_CURVE_IMPLEMENTATION_VERSION,
        SELECTIVE_TONE_IMPLEMENTATION_VERSION,
        PERCEPTUAL_COLOR_IMPLEMENTATION_VERSION,
        OKLAB_COLOR_WARPER_IMPLEMENTATION_VERSION,
        TECHNICAL_DETAIL_IMPLEMENTATION_VERSION,
        COLOR_GRADING_IMPLEMENTATION_VERSION,
        FINISHING_EFFECTS_IMPLEMENTATION_VERSION,
    ] {
        assert!(
            identity.ends_with("-v1"),
            "pre-release implementation identity escaped v1: {identity}"
        );
    }
}
