//! Background-safe planning and retention for local Catalog backups.
//!
//! `shadow_catalog` owns `SQLite`'s consistent-copy and restore-drill primitive.
//! This Core module adds application policy: unique managed filenames, bounded
//! best-effort retention, and low-priority scheduler admission. It deliberately
//! does not know about Qt notifications, settings persistence, or catalog schema
//! mutation.

use std::{
    cmp::Reverse,
    fs,
    path::{Path, PathBuf},
    sync::{
        Arc,
        atomic::{AtomicU64, Ordering},
    },
    time::{SystemTime, UNIX_EPOCH},
};

use shadow_catalog::{CatalogBackupError, CatalogBackupReceipt, create_catalog_backup};
use thiserror::Error;

use crate::{
    WorkOutcome, WorkPriority, WorkSchedulerHandle, WorkSubmitError, WorkTicket, WorkWaitError,
};

const DEFAULT_RETAIN_COUNT: usize = 8;
const MAX_DESTINATION_ATTEMPTS: usize = 1_024;

/// Application-owned selection of where and how many Catalog backups to keep.
///
/// Retention recognizes only filenames generated by [`CatalogBackupPlan`]. It
/// never deletes arbitrary `SQLite` files that happen to share the directory.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct CatalogBackupPolicy {
    directory: PathBuf,
    file_prefix: String,
    retain_count: usize,
}

impl CatalogBackupPolicy {
    #[must_use]
    pub fn new(directory: impl Into<PathBuf>) -> Self {
        Self {
            directory: directory.into(),
            file_prefix: "shadow".to_owned(),
            retain_count: DEFAULT_RETAIN_COUNT,
        }
    }

    /// Sets a visible, filesystem-safe prefix for new managed backup files.
    ///
    /// # Errors
    ///
    /// Returns [`CatalogBackupPolicyError::InvalidFilePrefix`] when the prefix
    /// would be ambiguous in a filename or retention scan.
    pub fn with_file_prefix(
        mut self,
        file_prefix: impl Into<String>,
    ) -> Result<Self, CatalogBackupPolicyError> {
        let file_prefix = file_prefix.into();
        validate_file_prefix(&file_prefix)?;
        self.file_prefix = file_prefix;
        Ok(self)
    }

    /// Sets the number of managed, verified backups to retain.
    ///
    /// At least one is required: a successful new backup is always protected
    /// from the retention pass that follows it.
    ///
    /// # Errors
    ///
    /// Returns [`CatalogBackupPolicyError::ZeroRetainCount`] for zero.
    pub fn with_retain_count(
        mut self,
        retain_count: usize,
    ) -> Result<Self, CatalogBackupPolicyError> {
        if retain_count == 0 {
            return Err(CatalogBackupPolicyError::ZeroRetainCount);
        }
        self.retain_count = retain_count;
        Ok(self)
    }

    #[must_use]
    pub fn directory(&self) -> &Path {
        &self.directory
    }

    #[must_use]
    pub fn file_prefix(&self) -> &str {
        &self.file_prefix
    }

    #[must_use]
    pub const fn retain_count(&self) -> usize {
        self.retain_count
    }
}

/// Configuration failures caught before a background backup is queued.
#[derive(Debug, Error, Clone, Eq, PartialEq)]
pub enum CatalogBackupPolicyError {
    #[error("catalog backup filename prefix must contain only ASCII letters, digits, '-' or '_'")]
    InvalidFilePrefix,
    #[error("catalog backup retention must keep at least one completed backup")]
    ZeroRetainCount,
}

/// A concrete destination chosen before a background backup starts.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct CatalogBackupPlan {
    pub source: PathBuf,
    pub destination: PathBuf,
    pub policy: CatalogBackupPolicy,
}

/// Verified backup receipt plus the non-critical result of the retention pass.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct CatalogBackupCompletion {
    pub receipt: CatalogBackupReceipt,
    pub retention: CatalogBackupRetention,
}

/// Conservative retention result for one successful backup.
///
/// A backup is successful even if an old file cannot be removed. The warning is
/// surfaced instead of hiding the newly verified backup from the caller.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct CatalogBackupRetention {
    pub retained_count: usize,
    pub removed: Vec<PathBuf>,
    pub warnings: Vec<String>,
}

/// Failure produced by the actual background copy job.
#[derive(Debug, Error)]
pub enum CatalogBackupJobError {
    #[error(transparent)]
    Backup(#[from] CatalogBackupError),
}

/// Failure before a backup job enters the scheduler.
#[derive(Debug, Error)]
pub enum CatalogBackupScheduleError {
    #[error("system clock is before the Unix epoch; cannot name a catalog backup")]
    ClockBeforeUnixEpoch,
    #[error(
        "could not choose a unique catalog backup destination after {MAX_DESTINATION_ATTEMPTS} attempts"
    )]
    DestinationExhausted,
    #[error(transparent)]
    Scheduler(#[from] WorkSubmitError),
}

/// One scheduler ticket paired with the immutable destination it will create.
#[derive(Debug)]
pub struct CatalogBackupJob {
    pub plan: CatalogBackupPlan,
    ticket: WorkTicket<Result<CatalogBackupCompletion, CatalogBackupJobError>>,
}

impl CatalogBackupJob {
    #[must_use]
    pub const fn id(&self) -> u64 {
        self.ticket.id()
    }

    pub fn cancel(&self) {
        self.ticket.cancel();
    }

    /// Waits for scheduler completion, cancellation, or a contained job error.
    ///
    /// # Errors
    ///
    /// Returns [`WorkWaitError`] only when the scheduler vanishes before it can
    /// report any terminal outcome.
    pub fn wait(
        self,
    ) -> Result<WorkOutcome<Result<CatalogBackupCompletion, CatalogBackupJobError>>, WorkWaitError>
    {
        self.ticket.wait()
    }

    /// Samples a terminal outcome without blocking the caller.
    ///
    /// # Errors
    ///
    /// Returns [`WorkWaitError`] only when the scheduler vanishes before it can
    /// report any terminal outcome.
    pub fn try_wait(
        &self,
    ) -> Result<
        Option<WorkOutcome<Result<CatalogBackupCompletion, CatalogBackupJobError>>>,
        WorkWaitError,
    > {
        self.ticket.try_wait()
    }
}

/// Schedules verified Catalog backups below visible preview and interaction work.
#[derive(Debug, Clone)]
pub struct CatalogBackupService {
    scheduler: WorkSchedulerHandle,
    policy: CatalogBackupPolicy,
    destination_sequence: Arc<AtomicU64>,
}

impl CatalogBackupService {
    #[must_use]
    pub fn new(scheduler: WorkSchedulerHandle, policy: CatalogBackupPolicy) -> Self {
        Self {
            scheduler,
            policy,
            destination_sequence: Arc::new(AtomicU64::new(0)),
        }
    }

    #[must_use]
    pub fn policy(&self) -> &CatalogBackupPolicy {
        &self.policy
    }

    /// Chooses a destination and queues a low-priority verified backup without
    /// blocking the caller.
    ///
    /// # Errors
    ///
    /// Returns [`CatalogBackupScheduleError::Scheduler`] when the shared bounded
    /// work queue is full or shutting down. The caller can then surface that
    /// condition and retry later without losing the current Catalog.
    pub fn try_schedule(
        &self,
        source: impl Into<PathBuf>,
    ) -> Result<CatalogBackupJob, CatalogBackupScheduleError> {
        let plan = self.plan(source.into())?;
        let scheduled_plan = plan.clone();
        let ticket = self.scheduler.try_submit(
            crate::WorkSpec::new(WorkPriority::BackgroundAnalysis),
            move |context| {
                let receipt =
                    create_catalog_backup(&scheduled_plan.source, &scheduled_plan.destination)?;
                let retention = if context.is_cancelled() {
                    CatalogBackupRetention {
                        retained_count: 1,
                        removed: Vec::new(),
                        warnings: vec![
                            "backup completed, but retention was skipped after cancellation"
                                .to_owned(),
                        ],
                    }
                } else {
                    prune_managed_backups(&scheduled_plan, &receipt.destination)
                };
                Ok(CatalogBackupCompletion { receipt, retention })
            },
        )?;
        Ok(CatalogBackupJob { plan, ticket })
    }

    fn plan(&self, source: PathBuf) -> Result<CatalogBackupPlan, CatalogBackupScheduleError> {
        let created_at_ms = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_err(|_| CatalogBackupScheduleError::ClockBeforeUnixEpoch)?
            .as_millis();
        for _ in 0..MAX_DESTINATION_ATTEMPTS {
            let sequence = self
                .destination_sequence
                .fetch_add(1, Ordering::Relaxed)
                .saturating_add(1);
            let filename = managed_backup_filename(
                self.policy.file_prefix(),
                created_at_ms,
                std::process::id(),
                sequence,
            );
            let destination = self.policy.directory().join(filename);
            if !destination.exists() {
                return Ok(CatalogBackupPlan {
                    source,
                    destination,
                    policy: self.policy.clone(),
                });
            }
        }
        Err(CatalogBackupScheduleError::DestinationExhausted)
    }
}

fn validate_file_prefix(file_prefix: &str) -> Result<(), CatalogBackupPolicyError> {
    if file_prefix.is_empty()
        || !file_prefix
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'_')
    {
        return Err(CatalogBackupPolicyError::InvalidFilePrefix);
    }
    Ok(())
}

fn managed_backup_filename(
    file_prefix: &str,
    created_at_ms: u128,
    process_id: u32,
    sequence: u64,
) -> String {
    format!("{file_prefix}-catalog-v1-{created_at_ms:020}-{process_id:010}-{sequence:020}.sqlite")
}

fn prune_managed_backups(
    plan: &CatalogBackupPlan,
    completed_destination: &Path,
) -> CatalogBackupRetention {
    let mut warnings = Vec::new();
    let source = plan.source.canonicalize().ok();
    let completed = completed_destination.canonicalize().ok();
    let entries = match fs::read_dir(plan.policy.directory()) {
        Ok(entries) => entries,
        Err(error) => {
            return CatalogBackupRetention {
                retained_count: 1,
                removed: Vec::new(),
                warnings: vec![format!(
                    "backup completed but retention could not read {}: {error}",
                    plan.policy.directory().display()
                )],
            };
        }
    };

    let mut candidates = Vec::new();
    for entry in entries {
        let entry = match entry {
            Ok(entry) => entry,
            Err(error) => {
                warnings.push(format!(
                    "retention skipped an unreadable directory entry: {error}"
                ));
                continue;
            }
        };
        let path = entry.path();
        if !entry.file_type().is_ok_and(|kind| kind.is_file()) {
            continue;
        }
        let Some(key) = managed_backup_key(path.file_name(), plan.policy.file_prefix()) else {
            continue;
        };
        let canonical = path.canonicalize().ok();
        if canonical.as_ref() == source.as_ref() {
            continue;
        }
        candidates.push(ManagedBackup {
            path,
            canonical,
            key,
        });
    }
    candidates.sort_unstable_by_key(|candidate| Reverse(candidate.key));

    let mut removed = Vec::new();
    let mut retained_count = 0_usize;
    // Reserve one retention slot for the backup that just passed its restore
    // drill even if a wall-clock correction makes an older filename sort later.
    let completed_is_managed = candidates
        .iter()
        .any(|candidate| candidate.canonical.as_ref() == completed.as_ref());
    let mut remaining = plan
        .policy
        .retain_count()
        .saturating_sub(usize::from(completed_is_managed));
    for candidate in candidates {
        let is_completed = candidate.canonical.as_ref() == completed.as_ref();
        if is_completed {
            retained_count = retained_count.saturating_add(1);
            continue;
        }
        if remaining > 0 {
            retained_count = retained_count.saturating_add(1);
            remaining = remaining.saturating_sub(1);
            continue;
        }
        match fs::remove_file(&candidate.path) {
            Ok(()) => removed.push(candidate.path),
            Err(error) => warnings.push(format!(
                "retention could not remove {}: {error}",
                candidate.path.display()
            )),
        }
    }

    CatalogBackupRetention {
        retained_count,
        removed,
        warnings,
    }
}

#[derive(Debug)]
struct ManagedBackup {
    path: PathBuf,
    canonical: Option<PathBuf>,
    key: ManagedBackupKey,
}

#[derive(Debug, Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
struct ManagedBackupKey {
    created_at_ms: u128,
    process_id: u32,
    sequence: u64,
}

fn managed_backup_key(
    file_name: Option<&std::ffi::OsStr>,
    file_prefix: &str,
) -> Option<ManagedBackupKey> {
    let file_name = file_name?.to_str()?;
    let stem = file_name.strip_suffix(".sqlite")?;
    let components = stem
        .strip_prefix(&format!("{file_prefix}-catalog-v1-"))?
        .split('-')
        .collect::<Vec<_>>();
    let [created_at_ms, process_id, sequence] = components.as_slice() else {
        return None;
    };
    Some(ManagedBackupKey {
        created_at_ms: created_at_ms.parse().ok()?,
        process_id: process_id.parse().ok()?,
        sequence: sequence.parse().ok()?,
    })
}

#[cfg(test)]
mod tests;
